### ISSUE TITLE
v-model not updating when tribute item is replaced

### ISSUE THREAD

**Issue by Trevash** [syropian/vue-tribute#35]
When I trigger an replace on the v-model using a trigger added in the tribute options it doesn't update the v-model until after I add another character. When I call a function with the @tribute-replaced event the v-model is not updated with the new code. If I call a function with this text before I insert or remove another character, the vue-tribute added text disappears. Is there a way to force the v-model data to update with the @tribute-replaced event or another way?

**Comment by syropian** [comment]
Hi! Thanks for the report. Could you create a [CodeSandbox](https://codesandbox.io/) reproducing the issue? Thanks!

**Comment by Trevash** [comment]
@syropian Here is the sandbox: https://codesandbox.io/s/happy-tdd-whf6h

Notice when the @ is triggered and a number is selected the string `selected` doesn't update until after another character is added. Because of the way the system is designed I am grabbing vue-tribute from unpkg.

**Comment by syropian** [comment]
Thanks! I definitely understand the problem now. Once I'm done work in a few hours, I'll see if I can find a fix for this.

**Comment by syropian** [comment]
@Trevash I just published `1.0.5`, could you give that a try?

**Comment by Trevash** [comment]
I explicitly grabbed 1.0.5 and I'm still experiencing the same bug. Thanks for your quick responses though!

**Comment by syropian** [comment]
@Trevash Are you sure? I just tried it out here and it seems to be working https://codesandbox.io/s/jovial-ishizaka-9kr3v

Type an `@` symbol and choose a person - the resulting v-model now updates immediately. Is that not the issue you were describing?

**Comment by Trevash** [comment]
Yeah, that is the issue I was describing. It works as expected when added as a dependency in the package.json but it does not when added as a script tag using unpkg. If you take a look at my code sandbox I have updated it to explicitly grab version `1.0.5` but still experience the same bug

**Comment by syropian** [comment]
@Trevash I think there's maybe some weird caching going on with your sandbox. I created one using the unpkg script, and it works fine. See https://codesandbox.io/s/zen-bas-p2l9j?file=/index.html

**Comment by Trevash** [comment]
I'm seeing the same issue on your sandbox?? 

Here is a picture of what happened after the tribute replace: 
![Capture](https://user-images.githubusercontent.com/13562006/86410560-35a00b80-bc78-11ea-8118-d44ee8854215.PNG)

**Comment by syropian** [comment]
@Trevash What web browser are you using? I feel like that must be the issue, since it is definitely working correctly for me in Chrome/Brave. See recording here

![](https://d.pr/i/mnVxIx+)

**Comment by Trevash** [comment]
I'm using Edge. Just tested it with Chrome and Firefox though and am getting the same issue. Sorry, this must be frustrating!

**Comment by syropian** [comment]
Hm, I just tried it in Safari and Firefox and it worked as intended there. I still think the unpkg script is maybe cached on your end. Try flushing your DNS cache, or maybe even restarting your machine. You could also try using the implicit unpkg url, to see if that makes a difference — https://unpkg.com/vue-tribute

**Comment by Trevash** [comment]
Found something interesting. Try to use the mouse to click on an item from the list. It looks like it adds it correctly if an item is selected with a tab select but not with a mouse click. This is only on the unpkg version.

![tab and mouse](https://user-images.githubusercontent.com/13562006/86407939-3da97c80-bc73-11ea-9b6c-8876c4045db4.gif)

I guess I have been using a mouse click the whole time which is why it was acting differently

**Comment by syropian** [comment]
Ah! That would explain it. Could you try `1.0.6` and see if it fixes the issue for you? I tried both keyboard and mouse, and it worked for me.

**Comment by Trevash** [comment]
Fantastic! It works. Thank you so much for helping me out! Of course we just happened to be using different methods to select items.

**Comment by syropian** [comment]
Awesome! Glad we got it sorted. It do be like that sometimes 🤪
